// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"

	mock "github.com/stretchr/testify/mock"
)

// ContactHandlerMock is an autogenerated mock type for the ContactHandler type
type ContactHandlerMock struct {
	mock.Mock
}

type ContactHandlerMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ContactHandlerMock) EXPECT() *ContactHandlerMock_Expecter {
	return &ContactHandlerMock_Expecter{mock: &_m.Mock}
}

// CreateContact provides a mock function with given fields: ectx
func (_m *ContactHandlerMock) CreateContact(ectx echo.Context) error {
	ret := _m.Called(ectx)

	if len(ret) == 0 {
		panic("no return value specified for CreateContact")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(ectx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ContactHandlerMock_CreateContact_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateContact'
type ContactHandlerMock_CreateContact_Call struct {
	*mock.Call
}

// CreateContact is a helper method to define mock.On call
//   - ectx echo.Context
func (_e *ContactHandlerMock_Expecter) CreateContact(ectx interface{}) *ContactHandlerMock_CreateContact_Call {
	return &ContactHandlerMock_CreateContact_Call{Call: _e.mock.On("CreateContact", ectx)}
}

func (_c *ContactHandlerMock_CreateContact_Call) Run(run func(ectx echo.Context)) *ContactHandlerMock_CreateContact_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(echo.Context))
	})
	return _c
}

func (_c *ContactHandlerMock_CreateContact_Call) Return(_a0 error) *ContactHandlerMock_CreateContact_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ContactHandlerMock_CreateContact_Call) RunAndReturn(run func(echo.Context) error) *ContactHandlerMock_CreateContact_Call {
	_c.Call.Return(run)
	return _c
}

// NewContactHandlerMock creates a new instance of ContactHandlerMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewContactHandlerMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ContactHandlerMock {
	mock := &ContactHandlerMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
